services:
  - type: web
    name: timetablebot-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_sender.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false

  - type: worker
    name: timetablebot-daily
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
    schedule: "CRON 30 1 * * *" # Runs daily at 7:00 AM IST (1:30 UTC)

  - type: worker
    name: timetablebot-hourly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python hourly_reminder.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
    schedule: "CRON */5 3-10 * * *" # Every 5 min, 8:30-16:29 IST (3:00-10:59 UTC)