name: Hourly Timetable Reminder

on:
  schedule:
    - cron: '30-59/5 3 * * *'   # 3:30, 3:35, ..., 3:55 UTC
    - cron: '*/5 4-9 * * *'     # 4:00, 4:05, ..., 9:55 UTC
    - cron: '0-30/5 10 * * *'   # 10:00, 10:05, ..., 10:30 UTC
  workflow_dispatch:

jobs:
  send-hourly-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run hourly reminder bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python hourly_reminder.py
