name: Hourly Timetable Reminder

on:
  schedule:
    # Runs every hour from 9:00 to 15:00 UTC (which is 9:00 to 16:00 IST)
    - cron: '0 3-10 * * *'  # 9:00 to 16:00 IST (IST = UTC+5:30, so 9:00 IST = 3:30 UTC, but GitHub Actions only supports full hours)
  workflow_dispatch:

jobs:
  send-hourly-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run hourly reminder bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: |
          python hourly_reminder.py
