name: Railway Collector Bot Scheduler

on:
  schedule:
    # Start at 8:00 AM UTC
    - cron: '0 8 * * *'
    # Stop at 8:00 PM UTC
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  control-railway-service:
    runs-on: ubuntu-latest
    steps:
      - name: Determine action (start or stop)
        id: action
        run: |
          if [[ "${{ github.event.schedule }}" == '0 8 * * *' ]]; then
            echo "::set-output name=action::start"
          else
            echo "::set-output name=action::stop"
          fi

      - name: Start or Stop Railway Service
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          ACTION="${{ steps.action.outputs.action }}"
          echo "Action is: $ACTION"
          if [ "$ACTION" = "start" ]; then
            curl -X POST \
              -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
              -H "Content-Type: application/json" \
              "https://backboard.railway.app/project/$RAILWAY_SERVICE_ID/service/$RAILWAY_SERVICE_ID/deploy"
          else
            curl -X POST \
              -H "Authorization: Bearer $RAILWAY_API_TOKEN" \
              -H "Content-Type: application/json" \
              "https://backboard.railway.app/project/$RAILWAY_SERVICE_ID/service/$RAILWAY_SERVICE_ID/stop" 