name: Send WhatsApp Timetable

on:
  schedule:
    # Runs every day at 8:00 AM UTC (adjust cron for your timezone)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  send-timetable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run timetable bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_WHATSAPP: ${{ secrets.TWILIO_FROM_WHATSAPP }}
          TWILIO_TO_WHATSAPP_LIST: ${{ secrets.TWILIO_TO_WHATSAPP_LIST }}
        run: |
          python main.py
